export const generationPageStyles = {
  page: 'mx-auto w-full max-w-dp-content px-0 py-1 text-dp-near-black',
  identity: 'border-b border-dp-border pb-6 max-md:pb-5 max-sm:pb-4',
  identityTop: 'flex flex-wrap items-start justify-between gap-5',
  eyebrow: 'm-0 text-[11px] font-semibold uppercase tracking-[0.16em] text-dp-muted',
  title: 'm-0 mt-2 text-[clamp(1.75rem,3vw,2rem)] font-bold leading-[1.05] tracking-[-0.05em] text-dp-black',
  intro: 'm-0 mt-2 max-w-[620px] text-[14px] leading-6 text-dp-text',
  statusBase: 'inline-flex min-h-8 items-center rounded-full border px-3 text-[12px] font-semibold',
  statusReady: 'border-dp-success-border bg-dp-success-surface text-dp-success-text',
  statusDraft: 'border-dp-border bg-dp-page text-dp-muted',
  statusGenerating: 'border-dp-border-dark bg-dp-surface text-dp-black',
  statusCompleted: 'border-dp-success-border bg-dp-success-surface text-dp-success-text',
  statusFailed: 'border-dp-error-border bg-dp-error-surface text-dp-error-text',
  statusUnknown: 'border-dp-border bg-dp-page text-dp-muted',
  layout: 'mt-5 grid grid-cols-[minmax(0,1fr)_360px] items-start gap-8 max-lg:grid-cols-1 max-lg:gap-5',
  stack: 'grid min-w-0 gap-5',
  panel: 'min-w-0 border-t border-dp-border bg-white pt-5 first:border-t-0 first:pt-0',
  panelHeader: 'mb-3',
  panelTitle: 'm-0 text-[18px] font-bold leading-tight tracking-[-0.03em] text-dp-black',
  panelDescription: 'm-0 mt-1 text-[13px] leading-5 text-dp-muted',
  promptText: 'm-0 max-w-[760px] border-l-2 border-dp-border-dark pl-4 whitespace-pre-wrap text-[15px] leading-7 text-dp-black max-sm:pl-3',
  summaryList: 'm-0 grid grid-cols-2 gap-x-8 p-0 max-sm:grid-cols-1',
  summaryItem: 'grid min-w-0 grid-cols-[minmax(78px,0.5fr)_minmax(0,1fr)] gap-3 border-t border-dp-border py-3 first:border-t-0 max-sm:grid-cols-[minmax(100px,0.42fr)_minmax(0,1fr)]',
  summaryItemWide: 'col-span-2 max-sm:col-span-1',
  summaryTerm: 'text-[11px] font-semibold uppercase tracking-[0.12em] text-dp-muted',
  summaryValue: 'm-0 min-w-0 text-[13px] font-medium leading-5 text-dp-black',
  notes: 'rounded-dp-control bg-dp-page px-3 py-2 text-dp-text',
  tagList: 'flex flex-wrap gap-1',
  tag: 'inline-flex max-w-full items-center rounded-full border border-dp-border bg-dp-page px-2 py-0.5 text-[11.5px] font-medium leading-5 text-dp-black',
  emptyText: 'm-0 text-[13px] leading-5 text-dp-muted',
  inspirationList: 'grid grid-cols-2 gap-3 max-md:grid-cols-1',
  inspirationReference: 'grid min-w-0 grid-cols-[82px_minmax(0,1fr)] items-center gap-3 border-t border-dp-border pt-3 first:border-t-0 max-md:first:border-t-0 max-sm:grid-cols-[72px_minmax(0,1fr)]',
  inspirationImage: 'aspect-[4/3] h-auto w-full rounded-lg border border-dp-border bg-dp-page object-cover',
  inspirationFallback: 'grid aspect-[4/3] h-auto w-full place-items-center rounded-lg border border-dashed border-dp-border bg-dp-page text-[11px] font-semibold text-dp-muted',
  inspirationBody: 'min-w-0',
  inspirationLabel: 'm-0 text-[10px] font-semibold uppercase tracking-[0.12em] text-dp-muted',
  inspirationId: 'm-0 mt-1 break-words text-[13.5px] font-semibold leading-5 text-dp-black',
  actionPanel: 'sticky top-[calc(var(--spacing-dp-header)+20px)] min-w-0 rounded-dp-control border border-dp-border bg-white p-6 shadow-dp-card max-lg:static max-sm:p-4',
  actionHeader: 'flex flex-wrap items-center justify-between gap-3',
  actionEyebrow: 'm-0 text-[10px] font-semibold uppercase tracking-[0.14em] text-dp-muted',
  actionTitle: 'm-0 mt-4 text-[22px] font-bold leading-tight tracking-[-0.04em] text-dp-black',
  actionCopy: 'm-0 mt-3 text-[13.5px] leading-6 text-dp-muted',
  actionButton: 'mt-6 inline-flex min-h-12 w-full cursor-not-allowed items-center justify-center rounded-dp-control border border-dp-black bg-dp-black px-5 py-2.5 text-sm font-semibold text-white opacity-50',
  actionLinks: 'mt-5 grid gap-2',
  primaryActionLink: 'inline-flex min-h-11 items-center justify-center rounded-dp-control border border-dp-black bg-dp-black px-5 py-2.5 text-sm font-semibold text-white no-underline transition-colors duration-200 hover:bg-neutral-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black focus-visible:ring-offset-2 focus-visible:ring-offset-white',
  secondaryActionLink: 'inline-flex min-h-10 items-center justify-center rounded-dp-control border border-dp-border bg-white px-4 py-2 text-[13px] font-semibold text-dp-black no-underline transition-colors duration-200 hover:border-dp-border-dark hover:bg-neutral-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black focus-visible:ring-offset-2 focus-visible:ring-offset-white',
  activity: 'mt-5 flex items-center gap-2 border-t border-dp-border pt-4 text-[12px] font-medium text-dp-text',
  activityDot: 'h-2 w-2 rounded-full bg-dp-black',
  stateWrap: 'grid min-h-[52vh] place-items-center rounded-dp-control border border-dp-border bg-white p-8 text-center shadow-dp-card max-sm:min-h-[58vh] max-sm:p-5',
  stateContent: 'max-w-[460px]',
  stateTitle: 'm-0 mt-3 text-[26px] font-bold tracking-[-0.045em] text-dp-black',
  stateText: 'm-0 mt-3 text-[14px] leading-6 text-dp-muted',
  stateActions: 'mt-6 flex flex-wrap justify-center gap-2',
  primaryStateButton: 'inline-flex min-h-10 items-center justify-center rounded-dp-control border border-dp-black bg-dp-black px-5 py-2.5 text-sm font-semibold text-white no-underline transition-colors duration-200 hover:bg-neutral-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black focus-visible:ring-offset-2 focus-visible:ring-offset-white',
  secondaryStateButton: 'inline-flex min-h-10 items-center justify-center rounded-dp-control border border-dp-border bg-white px-5 py-2.5 text-sm font-semibold text-dp-black no-underline transition-colors duration-200 hover:border-dp-border-dark hover:bg-neutral-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black focus-visible:ring-offset-2 focus-visible:ring-offset-white',
  loadingShell: 'grid gap-7',
  loadingHeader: 'border-b border-dp-border pb-6',
  loadingLayout: 'grid grid-cols-[minmax(0,1fr)_360px] items-start gap-8 max-lg:grid-cols-1 max-lg:gap-5',
  loadingStack: 'grid gap-5',
  loadingPanel: 'border-t border-dp-border pt-5 first:border-t-0 first:pt-0',
  skeletonLine: 'h-3 animate-pulse rounded-full bg-dp-surface',
  skeletonEyebrow: 'w-20',
  skeletonTitle: 'mt-4 h-10 w-2/3 max-sm:w-11/12',
  skeletonIntro: 'mt-4 h-3 w-3/4 max-sm:w-full',
  skeletonBlock: 'mt-5 h-24 animate-pulse rounded-dp-control bg-dp-page',
  skeletonRows: 'mt-5 grid gap-3',
}
