export const previewPageStyles = {
  page: 'mx-auto grid w-full max-w-dp-content gap-5 text-dp-near-black',
  workspaceBar: 'flex min-w-0 flex-wrap items-center justify-between gap-4 border-b border-dp-border pb-4',
  projectMeta: 'min-w-0',
  eyebrow: 'm-0 text-[10px] font-semibold uppercase tracking-[0.15em] text-dp-muted',
  projectName: 'm-0 mt-1 max-w-[min(60vw,560px)] truncate text-[20px] font-bold tracking-[-0.04em] text-dp-black',
  headerActions: 'flex flex-wrap items-center gap-3',
  status: 'inline-flex min-h-7 items-center gap-2 rounded-full border border-dp-success-border bg-dp-success-surface px-2.5 text-[11px] font-semibold text-dp-success-text',
  statusOther: 'border-dp-border bg-white text-dp-muted',
  statusDot: 'h-1.5 w-1.5 rounded-full bg-dp-success-text',
  tabs: 'flex items-center gap-1 rounded-dp-control border border-dp-border bg-white p-1',
  tab: 'inline-flex min-h-8 items-center rounded-[8px] px-3 text-[12px] font-semibold text-dp-muted',
  activeTab: 'bg-dp-black text-white',
  disabledTab: 'cursor-not-allowed opacity-45',
  backLink: 'inline-flex min-h-9 items-center rounded-dp-control border border-dp-border bg-white px-3 text-[12px] font-semibold text-dp-black no-underline transition-colors hover:bg-neutral-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black',
  workspace: 'grid min-h-[430px] grid-cols-[240px_minmax(0,1fr)] overflow-hidden rounded-dp-control border border-dp-border bg-white shadow-dp-card max-md:grid-cols-1',
  previewStage: 'flex min-h-[560px] min-w-0 flex-col overflow-hidden rounded-dp-control border border-dp-border bg-white shadow-dp-card',
  previewToolbar: 'flex flex-wrap items-center justify-between gap-3 border-b border-dp-border bg-white px-3 py-2.5',
  previewTabs: 'flex items-center gap-1 rounded-lg bg-dp-page p-1',
  previewTab: 'min-h-8 rounded-md px-3 text-[11px] font-semibold text-dp-muted transition-colors hover:text-dp-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black',
  previewTabActive: 'bg-white text-dp-black shadow-sm',
  deviceControls: 'flex items-center gap-1',
  deviceButton: 'min-h-8 rounded-md px-2.5 text-[10px] font-semibold text-dp-muted transition-colors hover:bg-dp-page focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black',
  deviceButtonActive: 'bg-dp-black text-white hover:bg-neutral-800',
  retryButton: 'min-h-8 rounded-md border border-dp-border px-3 text-[11px] font-semibold text-dp-black hover:bg-dp-page focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black',
  fileNameMode: 'max-w-[60%] truncate font-mono text-[10px] text-dp-muted',
  responsiveFrameStage: 'grid min-h-0 flex-1 justify-items-center gap-2 overflow-auto bg-[#eceeec] p-3 sm:p-5',
  responsiveFrameShell: 'relative min-h-[520px] overflow-hidden rounded-lg border border-dp-border bg-white shadow-[0_8px_28px_rgba(20,20,20,0.08)] transition-[width] duration-200',
  generatedFrame: 'block h-[min(72vh,900px)] min-h-[520px] w-full border-0 bg-white',
  runtimeOverlay: 'absolute inset-0 grid content-center justify-items-center gap-3 bg-white/90 text-[13px] font-medium text-dp-text',
  spinner: 'h-5 w-5 animate-spin rounded-full border-2 border-dp-border border-t-dp-black',
  runtimeError: 'absolute inset-0 grid content-center justify-items-center gap-3 overflow-auto bg-white p-6 text-center',
  runtimeErrorTitle: 'm-0 text-[17px] font-bold text-dp-black',
  runtimeErrorCopy: 'm-0 max-w-lg text-[12px] leading-5 text-dp-muted',
  detailsButton: 'rounded-md border border-dp-border px-3 py-1.5 text-[11px] font-semibold hover:bg-dp-page',
  runtimeDetails: 'max-h-32 max-w-full overflow-auto rounded-md bg-dp-page p-3 text-left font-mono text-[10px] text-dp-text',
  runtimeNote: 'm-0 text-[10px] leading-4 text-dp-muted',
  sourceInspection: 'min-h-[560px] overflow-hidden bg-[#151718]',
  fileRail: 'min-w-0 border-r border-dp-border bg-white max-md:border-r-0 max-md:border-b',
  railHeader: 'flex items-center justify-between border-b border-dp-border px-4 py-3',
  railTitle: 'm-0 text-[12px] font-bold text-dp-black',
  fileCount: 'text-[10px] font-semibold tabular-nums text-dp-muted',
  fileList: 'm-0 grid max-h-[380px] gap-0.5 overflow-y-auto p-2 max-md:max-h-40 max-md:grid-cols-2',
  fileButton: 'group flex min-w-0 cursor-pointer items-center gap-2 rounded-lg px-2.5 py-2 text-left text-[12px] text-dp-text transition-colors hover:bg-dp-page focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dp-black',
  selectedFileButton: 'bg-dp-page font-semibold text-dp-black',
  fileMark: 'h-1.5 w-1.5 shrink-0 rounded-full bg-dp-border-dark group-hover:bg-dp-black',
  selectedFileMark: 'bg-dp-black',
  fileName: 'min-w-0 truncate',
  previewCanvas: 'relative grid min-h-[430px] min-w-0 place-items-center overflow-hidden bg-[#f8f8f7] p-8 max-sm:min-h-[340px] max-sm:p-5',
  canvasGrid: 'pointer-events-none absolute inset-0 opacity-[0.34]',
  canvasContent: 'relative z-[1] w-full max-w-[520px] rounded-[14px] border border-dp-border bg-white p-6 shadow-[0_22px_65px_rgba(20,20,20,0.07)] max-sm:p-5',
  canvasTop: 'flex items-center justify-between gap-4 border-b border-dp-border pb-4',
  canvasBrand: 'flex items-center gap-2 text-[11px] font-bold tracking-[-0.02em] text-dp-black',
  brandMark: 'grid h-6 w-6 place-items-center rounded-[7px] bg-dp-black text-[10px] font-bold text-white',
  sourceLabel: 'rounded-full border border-dp-border bg-white px-2 py-1 text-[9px] font-semibold uppercase tracking-[0.1em] text-dp-muted',
  canvasHeading: 'm-0 mt-6 text-[22px] font-bold leading-tight tracking-[-0.045em] text-dp-black max-sm:text-[19px]',
  canvasCopy: 'm-0 mt-2 max-w-[420px] text-[12.5px] leading-5 text-dp-muted',
  canvasStats: 'mt-6 grid grid-cols-2 border-y border-dp-border py-3',
  canvasStat: 'min-w-0 border-r border-dp-border px-3 first:pl-0 last:border-r-0 last:pr-0',
  statValue: 'block text-[17px] font-bold tracking-[-0.04em] text-dp-black',
  statLabel: 'mt-1 block text-[9px] font-semibold uppercase tracking-[0.1em] text-dp-muted',
  previewNotice: 'mt-4 flex items-start gap-2.5 rounded-lg bg-dp-page p-3',
  noticeMark: 'mt-0.5 grid h-4 w-4 shrink-0 place-items-center rounded-full border border-dp-border-dark text-[9px] font-bold text-dp-black',
  noticeText: 'm-0 text-[10.5px] leading-[1.55] text-dp-text',
  selectedPanel: 'min-w-0 overflow-hidden rounded-dp-control border border-dp-border bg-[#151718] shadow-dp-card',
  selectedHeader: 'flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-4 py-3',
  selectedHeading: 'm-0 text-[12px] font-semibold text-white',
  selectedPath: 'mt-1 break-all font-mono text-[10px] text-white/50',
  language: 'rounded-full border border-white/15 px-2 py-1 font-mono text-[9px] uppercase text-white/65',
  codeScroll: 'max-h-[560px] overflow-auto',
  code: 'm-0 min-w-full p-5 font-mono text-[11.5px] leading-[1.75] text-[#d7ded9] selection:bg-white/20 max-sm:p-4 max-sm:text-[10.5px]',
  emptyCode: 'grid min-h-52 place-items-center p-5 text-center text-[12px] text-white/50',
  statePanel: 'grid min-h-[50vh] place-items-center rounded-dp-control border border-dp-border bg-white p-8 text-center shadow-dp-card max-sm:min-h-[55vh] max-sm:p-5',
  stateContent: 'max-w-[460px]',
  stateEyebrow: 'm-0 text-[10px] font-semibold uppercase tracking-[0.15em] text-dp-muted',
  stateTitle: 'm-0 mt-3 text-[24px] font-bold tracking-[-0.045em] text-dp-black',
  stateCopy: 'm-0 mt-2 text-[13px] leading-6 text-dp-muted',
  stateActions: 'mt-5 flex flex-wrap justify-center gap-2',
  primaryLink: 'inline-flex min-h-10 items-center justify-center rounded-dp-control border border-dp-black bg-dp-black px-4 text-[12px] font-semibold text-white no-underline hover:bg-neutral-800',
  secondaryLink: 'inline-flex min-h-10 items-center justify-center rounded-dp-control border border-dp-border bg-white px-4 text-[12px] font-semibold text-dp-black no-underline hover:bg-neutral-50',
  loadingPanel: 'grid min-h-[55vh] gap-5 rounded-dp-control border border-dp-border bg-white p-5',
  skeleton: 'animate-pulse rounded-lg bg-dp-page',
}
